version: '3.1'
volumes:
  db-data:
services:
  mysql:
    container_name: gu-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: gu_user
      MYSQL_PASSWORD: gu_pass
      TZ: Etc/GMT-2
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/:rw
      - db-data:/var/lib/mysql
